require('./gulp/tasks/del.coffee')
require('./gulp/tasks/browser-sync.coffee')
require('./gulp/tasks/copy.coffee')
require('./gulp/tasks/sass.coffee')
require('./gulp/tasks/webpack.coffee')
require('./gulp/tasks/typescript.coffee')
require('./gulp/tasks/watch.coffee')
require('./gulp/tasks/default.coffee')